version: '2'

services:
  zookeeper:
    image: registry.cn-beijing.aliyuncs.com/meigea/kafka:zk-2.12
    container_name: zk
    ports:
      - "2181:2181"
    networks:
      customize_net:
        ipv4_address: 192.168.99.81

  kafka:
    image: registry.cn-beijing.aliyuncs.com/meigea/kafka:2.5
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "http_log:1:3,security_log:1:1:compact"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      customize_net:
        ipv4_address: 192.168.99.100

networks:
  customize_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.99.0/24